# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad99f126f1f2f390a90ca78f4eeee5ed9b9ee651005d965f549981be1cde14e59d8c9a1bcc0e1c9d8372ed44ab88ee3b9e2e94a9c869c3066b1b8756decca41d

test:
  secret_key_base: c9c776154293ac3dadd8d2a9236a4ee4673302883b46db9b6c5d971f8a12e50d74a13cfde4ed2b6908aa576c4003b86771f07d1e7b34258fa423c674e4f49518

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
